GET http://localhost:8080/api/schools?city=miskolc
Accept: application/json

###
POST http://localhost:8080/api/schools/1/students
Content-Type: application/json

{
  "name": "",
  "dateOfBirth": "2006-06-25"
}

###
POST http://localhost:8080/api/schools
Content-Type: application/json

{
  "schoolName": "",
  "postalCode": "8000",
  "city": "Miskolc",
  "street": "Radnóti M.",
  "houseNumber": 7
}

###
PUT http://localhost:8080/api/schools/1/students/2
Content-Type: application/json
